name: Monthly Invoice Workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Validate secrets
        env:
            start_date: ${{ secrets.start_date }}
            interval_unit: ${{ secrets.interval_unit }}
            interval_quantity: ${{ secrets.interval_quantity }}
            name: ${{ secrets.name }}
            address_line_1: ${{ secrets.address_line_1 }}
            address_line_2: ${{ secrets.address_line_2 }}
            email: ${{ secrets.email }}
            phone: ${{ secrets.phone }}
            recipient: ${{ secrets.recipient }}
            recipient_address_line_1: ${{ secrets.recipient_address_line_1 }}
            recipient_address_line_2: ${{ secrets.recipient_address_line_2 }}
            recipient_email: ${{ secrets.recipient_email }}
            services_rendered: ${{ secrets.services_rendered }}
            amount_owed: ${{ secrets.amount_owed }}
            bank: ${{ secrets.bank }}
            routing_number: ${{ secrets.routing_number }}
            account_number: ${{ secrets.account_number }}
            email_server: ${{ secrets.email_server }}
            email_username: ${{ secrets.email_username }}
            email_password: ${{ secrets.email_password }}
        run: |
            if [ -z "${start_date}" ]; then echo "Missing secret: start_date"; exit 1; fi
            if [ -z "${interval_unit}" ]; then echo "Missing secret: interval_unit"; exit 1; fi
            if [ -z "${interval_quantity}" ]; then echo "Missing secret: interval_quantity"; exit 1; fi
            if [ -z "${name}" ]; then echo "Missing secret: name"; exit 1; fi
            if [ -z "${address_line_1}" ]; then echo "Missing secret: address_line_1"; exit 1; fi
            if [ -z "${address_line_2}" ]; then echo "Missing secret: address_line_2"; exit 1; fi
            if [ -z "${email}" ]; then echo "Missing secret: email"; exit 1; fi
            if [ -z "${phone}" ]; then echo "Missing secret: phone"; exit 1; fi
            if [ -z "${recipient}" ]; then echo "Missing secret: recipient"; exit 1; fi
            if [ -z "${recipient_address_line_1}" ]; then echo "Missing secret: recipient_address_line_1"; exit 1; fi
            if [ -z "${recipient_address_line_2}" ]; then echo "Missing secret: recipient_address_line_2"; exit 1; fi
            if [ -z "${recipient_email}" ]; then echo "Missing secret: recipient_email"; exit 1; fi
            if [ -z "${services_rendered}" ]; then echo "Missing secret: services_rendered"; exit 1; fi
            if [ -z "${amount_owed}" ]; then echo "Missing secret: amount_owed"; exit 1; fi
            if [ -z "${bank}" ]; then echo "Missing secret: bank"; exit 1; fi
            if [ -z "${routing_number}" ]; then echo "Missing secret: routing_number"; exit 1; fi
            if [ -z "${account_number}" ]; then echo "Missing secret: account_number"; exit 1; fi
            if [ -z "${email_server}" ]; then echo "Missing secret: email_server"; exit 1; fi
            if [ -z "${email_username}" ]; then echo "Missing secret: email_username"; exit 1; fi
            if [ -z "${email_password}" ]; then echo "Missing secret: email_password"; exit 1; fi

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1

      - name: Install project
        run: |
          poetry shell
          poetry install --no-interaction

      - name: Generate invoice
        run: |
          poetry shell
          python auto_invoicer/generate_invoice.py
        env:
          start_date: ${{ secrets.start_date }}
          interval_unit: ${{ secrets.interval_unit }}
          interval_quantity: ${{ secrets.interval_quantity }}
          name: ${{ secrets.name }}
          address_line_1: ${{ secrets.address_line_1 }}
          address_line_2: ${{ secrets.address_line_2 }}
          email: ${{ secrets.email }}
          phone: ${{ secrets.phone }}
          recipient: ${{ secrets.recipient }}
          recipient_address_line_1: ${{ secrets.recipient_address_line_1 }}
          recipient_address_line_2: ${{ secrets.recipient_address_line_2 }}
          recipient_email: ${{ secrets.recipient_email }}
          services_rendered: ${{ secrets.services_rendered }}
          amount_owed: ${{ secrets.amount_owed }}
          bank: ${{ secrets.bank }}
          routing_number: ${{ secrets.routing_number }}
          account_number: ${{ secrets.account_number }}
          email_server: ${{ secrets.email_server }}
          email_username: ${{ secrets.email_username }}
          email_password: ${{ secrets.email_password }}
